### ISSUE TITLE
import cudf occur the libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by honghh2018** [NVIDIA/cuda-samples#245]
Hi developer,
    Thanks to develop the great tools.

I want to install the cudf cudatookit through mamba install -c rapidsai -c nvidia -c conda-forge cudf=0.19 python=3.8 cudatoolkit=11.0 cuda command into our minconda environment.
but when i try to import the cudf into my python environment like import cudf, it show me below error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/apps/virtualEnv/miniconda3-py38/envs/huadaStereopy-st1/lib/python3.8/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/share/apps/virtualEnv/miniconda3-py38/envs/huadaStereopy-st1/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 18, in validate_setup
    from rmm._cuda.gpu import (
  File "/share/apps/virtualEnv/miniconda3-py38/envs/huadaStereopy-st1/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/share/apps/virtualEnv/miniconda3-py38/envs/huadaStereopy-st1/lib/python3.8/site-packages/rmm/mr.py", line 2, in <module>
    from rmm._lib.memory_resource import (
  File "/share/apps/virtualEnv/miniconda3-py38/envs/huadaStereopy-st1/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 3, in <module>
    from .device_buffer import DeviceBuffer
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
>>> 
The python version was 3.8
and the sys plotform was Centos7.9
how to fix this issue?
Any advice would be appreciated
Best,
hanhuihong

**Comment by rwarmstr** [comment]
We are unable to offer general installation assistance through this repo. If you're still having issues please consider opening a thread on the NVIDIA support forums.
